name: Azure login
runs:
  using: 'composite'
  steps:
  - name: Azure Login
    uses: azure/login@v1.6.1
    with:
      creds: |
        {
          "clientId": "${{ vars.WORKFLOW_AZURE_CLIENT_ID }}",
          "clientSecret": "${{ secrets.WORKFLOW_AZURE_CLIENT_SECRET }}",
          "subscriptionId": "${{ vars.WORKFLOW_AZURE_SUBSCRIPTION_ID }}",
          "tenantId": "${{ vars.WORKFLOW_AZURE_TENANT_ID }}"
        }