name: Set app version
inputs:
  app_version:
runs:
  steps:
  - name: Set app version
    shell: bash
    env:
      APP_VERSION: ${{ inputs.app_version }}
    run: |
      echo "New app version: $APP_VERSION"
      sed -i -znE -e "s|(.*<VersionPrefix>[[:space:]]*)([0-9]+\.[0-9]+\.[0-9]+)([[:space:]]*</VersionPrefix>.*)|\1$APP_VERSION\3|p" src/WebApplication1/WebApplication1.csproj
      git commit -a -m "Update version to $APP_VERSION"
      git push
