name: 21 Update environment

on:
  workflow_dispatch:
    inputs:
      ENV_NAME:
        description: Environment name
        type: environment
        required: true
  workflow_call:
    inputs:
      ENV_NAME:
        description: Environment name
        type: string
        required: true

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Prepare Terraform variables
        run: |
          echo 'APP_NAME="${{ vars.APP_NAME }}"' >> terraform.tfvars
          echo 'ENV_NAME="${{ inputs.ENV_NAME }}"' >> terraform.tfvars
          cat terraform.tfvars

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.0.0
        with:
          terraform_version: 1.7.0

      - name: Terraform init
        run: |
          export ARM_SUBSCRIPTION_ID="${{ vars.WORKFLOW_AZURE_SUBSCRIPTION_ID }}"
          export ARM_TENANT_ID="${{ vars.WORKFLOW_AZURE_TENANT_ID }}"
          export ARM_CLIENT_ID="${{ vars.WORKFLOW_AZURE_CLIENT_ID }}"
          export ARM_CLIENT_SECRET="${{ secrets.WORKFLOW_AZURE_CLIENT_SECRET }}"
          terraform init \
            -backend-config="resource_group_name=${{ vars.TERRAFORM_RESOURCE_GROUP_NAME }}" \
            -backend-config="storage_account_name=${{ vars.TERRAFORM_STORAGE_ACCOUNT_NAME }}" \
            -backend-config="container_name=${{ vars.TERRAFORM_STORAGE_CONTAINER_NAME }}" \
            -backend-config="key=${{ vars.APP_NAME }}-${{ inputs.ENV_NAME }}.tfstate"

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: |
          export ARM_SUBSCRIPTION_ID="${{ vars.WORKFLOW_AZURE_SUBSCRIPTION_ID }}"
          export ARM_TENANT_ID="${{ vars.WORKFLOW_AZURE_TENANT_ID }}"
          export ARM_CLIENT_ID="${{ vars.WORKFLOW_AZURE_CLIENT_ID }}"
          export ARM_CLIENT_SECRET="${{ secrets.WORKFLOW_AZURE_CLIENT_SECRET }}"
          terraform plan -out=tfplan

      - name: Upload Terraform files
        uses: actions/upload-artifact@v4.2.0
        with:
          name: tf-files
          path: |
            terraform.tfvars
            .terraform.lock.hcl
            tfplan

  terraform-apply:
    runs-on: ubuntu-latest
    needs: terraform-plan
    environment: ${{ inputs.ENV_NAME }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Download Terraform files
        uses: actions/download-artifact@v4.1.1
        with:
          name: tf-files

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.0.0
        with:
          terraform_version: 1.7.0

      - name: Terraform init
        run: |
          export ARM_SUBSCRIPTION_ID="${{ vars.WORKFLOW_AZURE_SUBSCRIPTION_ID }}"
          export ARM_TENANT_ID="${{ vars.WORKFLOW_AZURE_TENANT_ID }}"
          export ARM_CLIENT_ID="${{ vars.WORKFLOW_AZURE_CLIENT_ID }}"
          export ARM_CLIENT_SECRET="${{ secrets.WORKFLOW_AZURE_CLIENT_SECRET }}"
          terraform init \
            -backend-config="resource_group_name=${{ vars.TERRAFORM_RESOURCE_GROUP_NAME }}" \
            -backend-config="storage_account_name=${{ vars.TERRAFORM_STORAGE_ACCOUNT_NAME }}" \
            -backend-config="container_name=${{ vars.TERRAFORM_STORAGE_CONTAINER_NAME }}" \
            -backend-config="key=${{ vars.APP_NAME }}-${{ inputs.ENV_NAME }}.tfstate"

      - name: Terraform apply
        id: tf-apply
        run: |
          export ARM_SUBSCRIPTION_ID="${{ vars.WORKFLOW_AZURE_SUBSCRIPTION_ID }}"
          export ARM_TENANT_ID="${{ vars.WORKFLOW_AZURE_TENANT_ID }}"
          export ARM_CLIENT_ID="${{ vars.WORKFLOW_AZURE_CLIENT_ID }}"
          export ARM_CLIENT_SECRET="${{ secrets.WORKFLOW_AZURE_CLIENT_SECRET }}"
          terraform apply tfplan
          echo "RESOURCE_GROUP_NAME=$(terraform output -raw resource_group_name)" >> $GITHUB_OUTPUT
          echo "WEBAPP_NAME=$(terraform output -raw webapp_name)" >> $GITHUB_OUTPUT

      - name: Save environment variables
        env:
          GH_TOKEN: ${{ secrets.WORKFLOW_GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          ENV_NAME: ${{ inputs.ENV_NAME }}
          RESOURCE_GROUP_NAME: ${{ steps.tf-apply.outputs.RESOURCE_GROUP_NAME }}
          WEBAPP_NAME: ${{ steps.tf-apply.outputs.WEBAPP_NAME }}
        run: |
          gh variable set RESOURCE_GROUP_NAME -R $REPO -e $ENV_NAME -b $RESOURCE_GROUP_NAME
          gh variable set WEBAPP_NAME -R $REPO -e $ENV_NAME -b $WEBAPP_NAME

