name: 30 Delete environment

on:
  workflow_dispatch:
    inputs:
      ENV_NAME:
        description: Environment
        type: environment
        required: true

jobs:
  azure:
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENV_NAME }}
    steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3.0.0
      with:
        terraform_version: 1.7.0

    - name: Checkout repository
      uses: actions/checkout@v4.1.1

    - name: Delete Azure resources
      run: |
        cd terraform
        export ARM_SUBSCRIPTION_ID="${{ vars.WORKFLOW_AZURE_SUBSCRIPTION_ID }}"
        export ARM_TENANT_ID="${{ vars.WORKFLOW_AZURE_TENANT_ID }}"
        export ARM_CLIENT_ID="${{ vars.WORKFLOW_AZURE_CLIENT_ID }}"
        export ARM_CLIENT_SECRET="${{ secrets.WORKFLOW_AZURE_CLIENT_SECRET }}"

        echo '::group::Prepare Terraform variables'
        echo 'APP_NAME = "${{ vars.APP_NAME }}"' >> terraform.tfvars
        echo 'ENV_NAME = "${{ inputs.ENV_NAME }}"' >> terraform.tfvars
        cat ${{ vars.ENV_TYPE }}.tfvars >> terraform.tfvars
        cat terraform.tfvars
        echo '::endgroup::'

        echo '::group::Terraform init'
        terraform init \
          -backend-config="resource_group_name=${{ vars.TERRAFORM_RESOURCE_GROUP_NAME }}" \
          -backend-config="storage_account_name=${{ vars.TERRAFORM_STORAGE_ACCOUNT_NAME }}" \
          -backend-config="container_name=${{ vars.TERRAFORM_STORAGE_CONTAINER_NAME }}" \
          -backend-config="key=${{ vars.APP_NAME }}-${{ inputs.ENV_NAME }}.tfstate"
        echo '::endgroup::'

        echo '::group::Terraform destroy'
        terraform destroy --auto-approve
        echo '::endgroup::'

  github:
    needs: azure
    runs-on: ubuntu-latest
    steps:
    - name: Delete GitHub Environment
      env:
        GH_TOKEN: ${{ secrets.WORKFLOW_GITHUB_TOKEN }}
        ENV_NAME: ${{ inputs.ENV_NAME }}
        REPO: ${{ github.repository }}
      run: |
        gh api --method DELETE repos/$REPO/environments/$ENV_NAME

      
