name: 40 Build and Test

on:
  pull_request:
    branches:
      - "**"
    paths:
      - src/**
  push:
    branches:
      - main
      - release/**
    paths:
      - src/**
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:

      - run: echo "test"
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup .NET
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore src

      - name: Build
        run: dotnet build --no-restore src

      - name: Test
        run: dotnet test --no-build --verbosity normal src
