name: 50 Deploy branch snapshot
run-name: "${{ github.workflow }} [${{ inputs.ENV_NAME }}]"

on:
  workflow_dispatch:
    inputs:
      ENV_NAME:
        description: Environment name
        type: environment
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENV_NAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup .NET
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: 8.0.x

      - name: Build webapp
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/webapp -p:VersionSuffix=snapshot src/WebApplication1

      - name: Decode publish profile
        id: publish_profile
        env:
          AZURE_WEBAPP_PUBLISH_PROFILE_BASE64: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_BASE64 }}
        run: |
          AZURE_WEBAPP_PUBLISH_PROFILE=$(echo "$AZURE_WEBAPP_PUBLISH_PROFILE_BASE64" | base64 --decode)
          echo "AZURE_WEBAPP_PUBLISH_PROFILE=$AZURE_WEBAPP_PUBLISH_PROFILE" >> $GITHUB_OUTPUT

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: |
            {
              "clientId": "${{ vars.WORKFLOW_AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.WORKFLOW_AZURE_CLIENT_SECRET }}",
              "subscriptionId": "${{ vars.WORKFLOW_AZURE_SUBSCRIPTION_ID }}",
              "tenantId": "${{ vars.WORKFLOW_AZURE_TENANT_ID }}"
            }

      - name: Deploy webapp
        uses: azure/webapps-deploy@v3.0.0
        with:
          app-name: ${{ vars.WEBAPP_NAME }}
          publish-profile: ${{ steps.publish_profile.outputs.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{env.DOTNET_ROOT}}/webapp
