name: 60 Release

on:
  workflow_dispatch:

jobs:
  prepare_release:
    uses: ./.github/workflows/61-prepare-release.yml
    secrets: inherit

  build_release:
    needs: prepare_release
    uses: ./.github/workflows/62-build-release.yml
    secrets: inherit
    with:
      RELEASE_BRANCH: ${{ needs.prepare_release.outputs.RELEASE_BRANCH }}

  publish_release:
    needs: [prepare_release, build_release]
    uses: ./.github/workflows/63-publish-release.yml
    secrets: inherit
    with:
      RELEASE_BRANCH: ${{ needs.prepare_release.outputs.RELEASE_BRANCH }}