name: 60 Release

on:
  workflow_dispatch:

jobs:
  prepare-release:
    uses: ./.github/workflows/61-prepare-release.yml

  build-release:
    needs: prepare-release
    uses: ./.github/workflows/62-build-release.yml
    with:
      RELEASE_BRANCH: ${{ needs.prepare-release.outputs.RELEASE_BRANCH }}

  publish-release:
    needs: [prepare-release, build-release]
    uses: ./.github/workflows/63-publish-release.yml
    with:
      RELEASE_BRANCH: ${{ needs.prepare-release.outputs.RELEASE_BRANCH }}