name: 61 Prepare release

on:
  workflow_dispatch:
  workflow_call:
    outputs:
      RELEASE_VERSION:
        value: ${{ jobs.prepare-release.outputs.RELEASE_VERSION }}
      RELEASE_BRANCH:
        value: ${{ jobs.prepare-release.outputs.RELEASE_BRANCH }}

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    outputs:
      RELEASE_VERSION: ${{ steps.version.outputs.RELEASE_VERSION }}
      RELEASE_BRANCH: ${{ steps.release-branch.outputs.RELEASE_BRANCH }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1

    - name: Get version
      id: version
      run: |
        RELEASE_VERSION=$(sed -znE -e "s|.*<VersionPrefix>[[:space:]]*([0-9]+\.[0-9]+\.[0-9]+)[[:space:]]*</VersionPrefix>.*|\1|p" src/WebApplication1/WebApplication1.csproj)
        [[ -z $RELEASE_VERSION ]] && (echo "::error::Version not found" && exit 1)

        echo "Current version $RELEASE_VERSION"
        echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_OUTPUT

        RELEASE_MAJOR=$(echo $RELEASE_VERSION | sed -nE "s|([0-9]+)\.([0-9]+)\.([0-9]+)|\1|p")
        RELEASE_MINOR=$(echo $RELEASE_VERSION | sed -nE "s|([0-9]+)\.([0-9]+)\.([0-9]+)|\2|p")
        RELEASE_PATCH=$(echo $RELEASE_VERSION | sed -nE "s|([0-9]+)\.([0-9]+)\.([0-9]+)|\3|p")
        echo "RELEASE_MAJOR=$RELEASE_MAJOR" >> $GITHUB_OUTPUT
        echo "RELEASE_MINOR=$RELEASE_MINOR" >> $GITHUB_OUTPUT
        echo "RELEASE_PATCH=$RELEASE_PATCH" >> $GITHUB_OUTPUT


    - name: Resolve branch
      id: release-branch
      env:
        RELEASE_MAJOR: ${{ steps.version.outputs.RELEASE_MAJOR }}
        RELEASE_MINOR: ${{ steps.version.outputs.RELEASE_MINOR }}
      run: |
        RELEASE_BRANCH="release/$RELEASE_MAJOR.$RELEASE_MINOR"
        echo "RELEASE_BRANCH=$RELEASE_BRANCH" >> $GITHUB_OUTPUT
        echo "Branch: $RELEASE_BRANCH"

    - name: Set Git user info
      if: ${{ github.ref_name == 'main' }}
      run: |
        git config user.name "Workflow"
        git config user.email ""

    - name: Create release branch
      if: ${{ github.ref_name == 'main' }}
      env:
        RELEASE_BRANCH: ${{ steps.release-branch.outputs.RELEASE_BRANCH }}
      run: |
        echo "Create release branch $RELEASE_BRANCH"
        git switch -c $RELEASE_BRANCH
        echo "Push release branch to origin"
        git push --set-upstream origin $RELEASE_BRANCH
        echo "Switch back to current branch"
        git switch $GITHUB_REF_NAME

    - name: Bump minor version
      if: ${{ github.ref_name == 'main' }}
      env:
        RELEASE_MAJOR: ${{ steps.version.outputs.RELEASE_MAJOR }}
        RELEASE_MINOR: ${{ steps.version.outputs.RELEASE_MINOR }}
        RELEASE_PATCH: ${{ steps.version.outputs.RELEASE_PATCH }}
      run: |
        NEXT_MAJOR=$RELEASE_MAJOR
        NEXT_MINOR=$(echo $RELEASE_MINOR | awk '{$NF += 1 ; print}')
        NEXT_PATCH="0"
        NEXT_VERSION="$NEXT_MAJOR.$NEXT_MINOR.$NEXT_PATCH"
        echo "Next main version: $NEXT_VERSION"
        
        sed -i -znE -e "s|(.*<VersionPrefix>[[:space:]]*)([0-9]+\.[0-9]+\.[0-9]+)([[:space:]]*</VersionPrefix>.*)|\1$NEXT_VERSION\3|p" src/WebApplication1/WebApplication1.csproj
        git commit -a -m "Update version to $NEXT_VERSION"
        git push

    - name: GitHub draft release
      env:
        GH_TOKEN: ${{ secrets.WORKFLOW_GITHUB_TOKEN }}
        RELEASE_VERSION: ${{ steps.version.outputs.RELEASE_VERSION }}
        RELEASE_BRANCH: ${{ steps.version.outputs.RELEASE_BRANCH }}
      run: |
        gh release create "$RELEASE_VERSION" --target $RELEASE_BRANCH --draft