name: 62 Build release

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      release_branch:
        type: string

jobs:
  build_release:
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/actions/assert-main-or-release-branch
    
    - name: Resolve branch
      id: release_branch
      env:
        RELEASE_BRANCH: ${{ inputs.release_branch }}
      run: |
        [[ -z $RELEASE_BRANCH ]] && RELEASE_BRANCH=$GITHUB_REF_NAME
        echo "release_branch=$RELEASE_BRANCH" >> $GITHUB_OUTPUT
        echo "Branch: $RELEASE_BRANCH"

    - name: Checkout
      uses: actions/checkout@v4.1.1
      with:
        ref: ${{ steps.release_branch.outputs.release_branch }}

    - name: Get app version
      id: app_version
      uses: ./.github/actions/get-app-version
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: 8.0.x

    - name: Build webapp
      env:
        OUTPUT_DIR: ${{ env.DOTNET_ROOT }}
      run: dotnet publish -c Release -o $OUTPUT_DIR/webapp src/WebApplication1

    - name: Upload webapp to release
      env:
        GH_TOKEN: ${{ secrets.WORKFLOW_GITHUB_TOKEN }}
        RELEASE_TAG: ${{ steps.app_version.outputs.current_app_version }}
        OUTPUT_DIR: ${{ env.DOTNET_ROOT }}
      run: |
        pushd $OUTPUT_DIR/webapp
        zip -r ../webapp.zip .
        popd
        gh release upload $RELEASE_TAG $OUTPUT_DIR/webapp.zip