name: 63 Publish release

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      release_branch:
        type: string

jobs:
  publish_release:
    runs-on: ubuntu-latest
    steps:
    - run: |
        [[ "$GITHUB_REF_NAME" =~ ^(main)|(release/[0-9]+\.[0-9]+)$ ]] \
        || (echo "::error::Workflow should only be run on main and release branches." && exit 1)

    - name: Resolve branch
      id: release_branch
      env:
        RELEASE_BRANCH: ${{ inputs.release_branch }}
      run: |
        [[ -z $RELEASE_BRANCH ]] && RELEASE_BRANCH=$GITHUB_REF_NAME
        echo "release_branch=$RELEASE_BRANCH" >> $GITHUB_OUTPUT
        echo "Branch: $RELEASE_BRANCH"

    - name: Checkout
      uses: actions/checkout@v4.1.1
      with:
        ref: ${{ steps.release_branch.outputs.release_branch }}
    
    - name: Get version
      id: app_version
      uses: ./.github/actions/get-app-version

    - name: Publish GitHub release
      env:
        GH_TOKEN: ${{ secrets.WORKFLOW_GITHUB_TOKEN }}
        RELEASE_TAG: ${{ steps.app_version.outputs.current_app_version }}
      run: gh release edit $RELEASE_TAG --draft=false

    - name: Set Git user info
      run: |
        git config user.name "Workflow"
        git config user.email ""

    - name: Bump patch version
      uses: ./.github/actions/set-app-version
      with:
        app_version: ${{ steps.app_version.outputs.next_patch_app_version }}