name: 70 Deploy release
run-name: "${{ github.workflow }} ${{ github.ref_name }} [${{ inputs.ENV_NAME }}]"

on:
  workflow_dispatch:
    inputs:
      ENV_NAME:
        description: Environment name
        type: environment
        required: true

jobs:
  deploy_release:
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENV_NAME }}
    steps:
    - run: |
        [[ "$GITHUB_REF_NAME" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] \
        || (echo "::error::Workflow should only be run on release tags." && exit 1)

    - name: Setup .NET
      uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: 8.0.x

    - name: Download webapp from release
      env:
        GH_TOKEN: ${{ secrets.WORKFLOW_GITHUB_TOKEN }}
        RELEASE_TAG: ${{ github.ref_name }}
        OUTPUT_DIR: ${{ env.DOTNET_ROOT }}
      run: |
        gh release download $RELEASE_TAG -p webapp.zip -d $OUTPUT_DIR
        pushd $OUTPUT_DIR
        mkdir webapp
        unzip webapp.zip -d webapp
        popd

    - name: Decode publish profile
      id: publish_profile
      env:
        AZURE_WEBAPP_PUBLISH_PROFILE_BASE64: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_BASE64 }}
      run: |
        AZURE_WEBAPP_PUBLISH_PROFILE=$(echo "$AZURE_WEBAPP_PUBLISH_PROFILE_BASE64" | base64 --decode)
        echo "AZURE_WEBAPP_PUBLISH_PROFILE=$AZURE_WEBAPP_PUBLISH_PROFILE" >> $GITHUB_OUTPUT

    - name: Azure Login
      uses: azure/login@v1.6.1
      with:
        creds: |
          {
            "clientId": "${{ vars.WORKFLOW_AZURE_CLIENT_ID }}",
            "clientSecret": "${{ secrets.WORKFLOW_AZURE_CLIENT_SECRET }}",
            "subscriptionId": "${{ vars.WORKFLOW_AZURE_SUBSCRIPTION_ID }}",
            "tenantId": "${{ vars.WORKFLOW_AZURE_TENANT_ID }}"
          }

    - name: Deploy webapp
      uses: azure/webapps-deploy@v3.0.0
      with:
        app-name: ${{ vars.WEBAPP_NAME }}
        publish-profile: ${{ steps.publish_profile.outputs.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{env.DOTNET_ROOT}}/webapp