name: Create new environment

on:
  workflow_dispatch:
    inputs:
      name:
        description: Environment name
        type: string
        required: true

jobs:
  azure:
    runs-on: ubuntu-latest
    environment: root
    outputs:
      RESOURCE_GROUP_NAME: ${{ steps.az-script.outputs.RESOURCE_GROUP_NAME }}
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI script
        id: az-script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az account show
            az storage -h
            RESOURCE_GROUP_NAME=webapp-${{ inputs.name }}-rg
            STORAGE_ACCOUNT_NAME=tfstate$RANDOM
            CONTAINER_NAME=tfstate
            echo "RESOURCE_GROUP_NAME=$RESOURCE_GROUP_NAME" >> $GITHUB_OUTPUT
  #            az group create --name $RESOURCE_GROUP_NAME --location euwest
  #            az storage account create --resource-group $RESOURCE_GROUP_NAME --name $STORAGE_ACCOUNT_NAME --sku Standard_LRS --encryption-services blob
  #            az storage container create --name $CONTAINER_NAME --account-name $STORAGE_ACCOUNT_NAME

  github:
    runs-on: ubuntu-latest
    needs: azure
    # Specifying a non-existing environment will create it in GitHub
    environment: ${{ inputs.name }}
    steps:
      - run: echo ${{ needs.azure.outputs.RESOURCE_GROUP_NAME }}
