name: Create new environment

on:
  workflow_dispatch:
    inputs:
      ENV_NAME:
        description: Environment name
        type: string
        required: true

jobs:
  create-env:
    runs-on: ubuntu-latest
    environment: root

    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/CLI@v1
        env:
          # the token must have read and write permissions to "Administration", "Environment", "Secrets" and "Variables"
          GH_TOKEN: ${{ secrets.ENV_CREATION_TOKEN }}
        with:
          azcliversion: 2.56.0
          inlineScript: |
            [[ "${{ inputs.ENV_NAME }}" =~ ^[a-zA-Z][a-zA-Z0-9]*$ ]] || (echo "::error::Environment name must start with a letter and only contain letters and numbers" && exit 1)

            ENV_NAME="${{ inputs.ENV_NAME }}"
            RESOURCE_GROUP_NAME=webapp-$ENV_NAME-rg
            TERRAFORM_STORAGE_ACCOUNT_NAME=terraform$RANDOM
            TERRAFORM_STORAGE_CONTAINER_NAME=terraform
            REPO=${{ github.repository }}

            echo "# CREATE GITHUB ENV"
            gh api --method PUT repos/$REPO/environments/$ENV_NAME

            echo "# SAVE VARIABLES"
            gh variable set RESOURCE_GROUP_NAME -R $REPO -e $ENV_NAME --body "$RESOURCE_GROUP_NAME"
            gh variable set TERRAFORM_STORAGE_ACCOUNT_NAME -R $REPO -e $ENV_NAME --body "$TERRAFORM_STORAGE_ACCOUNT_NAME"
            gh variable set TERRAFORM_STORAGE_CONTAINER_NAME -R $REPO -e $ENV_NAME --body "$TERRAFORM_STORAGE_CONTAINER_NAME"

            echo "# CREATE AZURE RESOURCE GROUP"
            az group create --name $RESOURCE_GROUP_NAME --location westeurope

            echo "# CREATE TERRAFORM STORAGE ACCOUNT"
            az storage account create --resource-group $RESOURCE_GROUP_NAME --name $TERRAFORM_STORAGE_ACCOUNT_NAME --sku Standard_LRS --encryption-services blob

            echo "# CREATE TERRAFORM STORAGE CONTAINER"
            az storage container create --name $CONTAINER_NAME --account-name $TERRAFORM_STORAGE_ACCOUNT_NAME --auth-mode login

            echo "# SAVE TERRAFORM STORAGE ACCESS KEY"
            ACCESS_KEY=$(az storage account keys list --resource-group $RESOURCE_GROUP_NAME --account-name $TERRAFORM_STORAGE_ACCOUNT_NAME --query '[0].value' -o tsv)
            echo "::add-mask::$ACCESS_KEY"
            gh secret set TERRAFORM_STORAGE_ACCOUNT_ACCESS_KEY -R $REPO -e $ENV_NAME --body "$ACCESS_KEY"
