name: Deploy snapshot to Development

env:
  AZURE_WEBAPP_NAME: dev-webapp-pfm
  WEBAPP_FOLDER: src/WebApplication1/WebApplication1

on:
  push:
    branches:
      - main
      - build-pipeline
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Setup Nuget Cache
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Make version numbers
        id: version-numbers
        run: |
          MAJOR=0
          MINOR=0
          PATCH=0
          SECONDS_SINCE_2000=$(($(date +%s) - $(date --date=000101 +%s)))
          DAYS_SINCE_2000=$(($SECONDS_SINCE_2000 / (60*60*24)))
          SECONDS_SINCE_MIDNIGHT_DIVIDED_BY_2=$(( ($SECONDS_SINCE_2000 % (60*60*24)) / 2 ))
          echo "assembly_version=$MAJOR.$MINOR.$BUILD_NUMBER.$SECONDS_SINCE_MIDNIGHT_DIVIDED_BY_2" >> $GITHUB_OUTPUT
          echo "package_version=$MAJOR.$MINOR.$PATCH-build${{github.run_id}}" >> $GITHUB_OUTPUT

      - name: Publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/webapp -p:AssemblyVersion=$ASSEMBLY_VERSION -p:AssemblyFileVersion=$ASSEMBLY_VERSION -p:Version=$PACKAGE_VERSION ${{ env.WEBAPP_FOLDER }}
        env:
          ASSEMBLY_VERSION: ${{ steps.version-numbers.outputs.assembly_version }}
          PACKAGE_VERSION: ${{ steps.version-numbers.outputs.package_version }}

      - name: Upload webapp artifact
        uses: actions/upload-artifact@v3
        with:
          name: webapp
          path: ${{env.DOTNET_ROOT}}/webapp

  deploy-development:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Development"
      url: ${{ steps.deploy-webapp.outputs.webapp-url }}
    steps:
      - name: Download webapp artifact
        uses: actions/download-artifact@v3
        with:
          name: webapp
          path: webapp

      - name: Deploy
        id: deploy-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: webapp
