name: Deploy snapshot to Development

env:
  AZURE_WEBAPP_NAME: dev-webapp-pfm
  WEBAPP_FOLDER: src/WebApplication1/WebApplication1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Setup Nuget Cache
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Make version numbers
        id: version-numbers
        run: |
          echo "version-number=0.0.1" >> $GITHUB_OUTPUT
          echo "version-text=0.0.1-snapshot $(date --utc +'%Y-%m-%d %H:%M UTC')" >> $GITHUB_OUTPUT

      - name: Publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/webapp -p:AssemblyVersion=$VERSION_NUMBER -p:Version=\"$VERSION_TEXT\" ${{ env.WEBAPP_FOLDER }}
        env:
          VERSION_NUMBER: ${{ steps.version-numbers.outputs.version-number }}
          VERSION_TEXT: ${{ steps.version-numbers.outputs.version-text }}

      - name: Upload webapp artifact
        uses: actions/upload-artifact@v3
        with:
          name: webapp
          path: ${{env.DOTNET_ROOT}}/webapp

  deploy-development:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Development"
      url: ${{ steps.deploy-webapp.outputs.webapp-url }}
    steps:
      - name: Download webapp artifact
        uses: actions/download-artifact@v3
        with:
          name: webapp
          path: webapp

      - name: Deploy
        id: deploy-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: webapp
