name: Deploy to Development

on:
  push:
    branches:
      - old_main
  workflow_dispatch:

jobs:
  build-and-deploy-to-dev:
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup .NET
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: 8.0.x

      - name: Build webapp
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/webapp -p:VersionSuffix=snapshot src/WebApplication1/WebApplication1

      - name: Deploy webapp
        id: deploy-webapp
        uses: azure/webapps-deploy@v3.0.0
        with:
          app-name: dev-webapp-pfm
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{env.DOTNET_ROOT}}/webapp
