name: Terraform

on:
  workflow_dispatch:
    inputs:
      ENV_NAME:
        description: Environment name
        type: environment
        required: true

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Prepare Terraform variables
        run: |
          echo 'APP_NAME="${{ vars.APP_NAME }}"' >> terraform.tfvars
          echo 'ENV_NAME="${{ inputs.ENV_NAME }}"' >> terraform.tfvars

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: |
            {
              "clientId": "${{ vars.WORKFLOW_AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.WORKFLOW_AZURE_CLIENT_SECRET }}",
              "subscriptionId": "${{ vars.WORKFLOW_AZURE_SUBSCRIPTION_ID }}",
              "tenantId": "${{ vars.WORKFLOW_AZURE_TENANT_ID }}"
            }

      - name: Get backend access key from Azure
        id: access-key
        uses: azure/CLI@v1
        with:
          azcliversion: 2.56.0
          inlineScript: |
            ARM_ACCESS_KEY=$(az storage account keys list --resource-group ${{ vars.TERRAFORM_RESOURCE_GROUP_NAME }} --account-name ${{ vars.TERRAFORM_STORAGE_ACCOUNT_NAME }} --query '[0].value' -o tsv)
            echo "::add-mask::$ARM_ACCESS_KEY"
            echo "ARM_ACCESS_KEY=$ARM_ACCESS_KEY" >> $GITHUB_OUTPUT

      - name: Terraform Init
        run: |
          export ARM_ACCESS_KEY=${{ steps.access-key.outputs.ARM_ACCESS_KEY }}
          terraform init \
            -backend-config="resource_group_name=${{ vars.TERRAFORM_RESOURCE_GROUP_NAME }}" \
            -backend-config="storage_account_name=${{ vars.TERRAFORM_STORAGE_ACCOUNT_NAME }}" \
            -backend-config="container_name=${{ vars.TERRAFORM_STORAGE_CONTAINER_NAME }}" \
            -backend-config="key=${{ vars.APP_NAME }}-${{ inputs.ENV_NAME }}.tfstate"

      - name: Upload .terraform.lock.hcl
        uses: actions/upload-artifact@v3
        with:
          name: .terraform.lock.hcl
          path: .terraform.lock.hcl

      - name: Terraform Plan
        run: |
          export ARM_SUBSCRIPTION_ID="${{ vars.WORKFLOW_AZURE_SUBSCRIPTION_ID }}"
          export ARM_TENANT_ID="${{ vars.WORKFLOW_AZURE_TENANT_ID }}"
          export ARM_CLIENT_ID="${{ vars.WORKFLOW_AZURE_CLIENT_ID }}"
          export ARM_CLIENT_SECRET="${{ secrets.WORKFLOW_AZURE_CLIENT_SECRET }}"
          terraform plan

      - name: Terraform Apply
        run: |
          export ARM_SUBSCRIPTION_ID="${{ vars.WORKFLOW_AZURE_SUBSCRIPTION_ID }}"
          export ARM_TENANT_ID="${{ vars.WORKFLOW_AZURE_TENANT_ID }}"
          export ARM_CLIENT_ID="${{ vars.WORKFLOW_AZURE_CLIENT_ID }}"
          export ARM_CLIENT_SECRET="${{ secrets.WORKFLOW_AZURE_CLIENT_SECRET }}"
          terraform apply
