name: Update webapp publish profile

on:
  workflow_dispatch:
    inputs:
      ENV_NAME:
        description: Environment name
        type: environment
        required: true
  workflow_call:
    inputs:
      ENV_NAME:
        description: Environment name
        type: string
        required: true

jobs:
  webapp-publish-profile:
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENV_NAME }}
    steps:
      - name: Azure Login
        uses: azure/login@v1.6.1
        with:
          creds: |
            {
              "clientId": "${{ vars.WORKFLOW_AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.WORKFLOW_AZURE_CLIENT_SECRET }}",
              "subscriptionId": "${{ vars.WORKFLOW_AZURE_SUBSCRIPTION_ID }}",
              "tenantId": "${{ vars.WORKFLOW_AZURE_TENANT_ID }}"
            }

      - name: Get webapp publish profile from Azure
        id: publish-profile
        uses: azure/CLI@v1.0.9
        with:
          azcliversion: 2.56.0
          inlineScript: |
            WEBAPP_PUBLISH_PROFILE=$(az webapp deployment list-publishing-profiles --xml --name "${{ vars.WEBAPP_NAME }}" --resource-group "${{ vars.RESOURCE_GROUP_NAME }}")
            WEBAPP_PUBLISH_PROFILE_BASE64=$(echo $WEBAPP_PUBLISH_PROFILE | base64)
            echo "::add-mask::$WEBAPP_PUBLISH_PROFILE_BASE64"
            echo "WEBAPP_PUBLISH_PROFILE_BASE64=$WEBAPP_PUBLISH_PROFILE_BASE64" >> $GITHUB_OUTPUT

      - name: Save webapp publish profile in GitHub environment secret
        env:
          GH_TOKEN: ${{ secrets.WORKFLOW_GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          ENV_NAME: ${{ inputs.ENV_NAME }}
          WEBAPP_PUBLISH_PROFILE_BASE64: ${{ steps.publish-profile.outputs.WEBAPP_PUBLISH_PROFILE_BASE64 }}
        run: |
          gh secret set WEBAPP_PUBLISH_PROFILE_BASE64 -R $REPO -e $ENV_NAME -b $WEBAPP_PUBLISH_PROFILE_BASE64
